services:

  frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "127.0.0.1:3003:3000"
    environment:
      - ALLOWED_DEV_ORIGINS=${ALLOWED_DEV_ORIGINS}
      - NEXT_PUBLIC_BASE_PATH=${NEXT_PUBLIC_BASE_PATH:-/ai}
      - WATCHPACK_POLLING=true  
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5  

  mongodb:
    image: mongo:8
    container_name: mongodb
    restart: unless-stopped
    command: ["mongod", "--auth"]
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh -u $$MONGO_INITDB_ROOT_USERNAME -p $$MONGO_INITDB_ROOT_PASSWORD --authenticationDatabase admin --eval 'db.adminCommand({ ping: 1 })' || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 5


  backend:
    build: ./backend
    container_name: ai-api
    ports:
      - "127.0.0.1:8003:8000"
    env_file:
      - ./backend/.env.docker
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7
    container_name: ai-redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  postgres_data:  
  mongodb_data:
