services:

  frontend:
    build: ./frontend
    container_name: ai-frontend
    ports:
      - "3003:3000"
    environment:
      - WATCHPACK_POLLING=true  
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend

  postgres:
    image: pgvector/pgvector:pg16
    container_name: ai-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ai_platform
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5  

  backend:
    build: ./backend
    container_name: ai-api
    ports:
      - "8003:8000"
    env_file:
      - ./backend/.env.docker
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/ai_platform
    volumes:
      - ./backend:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started

  redis:
    image: redis:7
    container_name: ai-redis
    ports:
      - "6379:6379"

  # ollama:
  #   image: ollama/ollama
  #   container_name: ai-ollama
  #   volumes:
  #     - D:/OllamaModels:/root/.ollama  # 這行就是「外面掛載儲存」
  #   ports:
  #     - "11434:11434"