name: Local Deploy Test

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create compose env
        shell: powershell
        run: |
          @"
          ${{ secrets.COMPOSE_ENV }}
          "@ | Out-File .env -Encoding utf8 

      - name: Create backend env
        shell: powershell
        run: |
          @"
          ${{ secrets.BACKEND_ENV }}
          "@ | Out-File backend/.env.docker -Encoding utf8

      - name: Create frontend env
        shell: powershell
        run: |
          @"
          ${{ secrets.FRONTEND_ENV }}
          "@ | Out-File frontend/.env -Encoding utf8    

      - name: Deploy
        shell: powershell
        run: |
          cd $env:GITHUB_WORKSPACE

          docker compose down
          docker compose up -d --build